name: gloss
version: 0.1.3
author: Yehor Lvivski <lvivski@gmail.com>
description: Glamorous CSS preprocessor
homepage: http://github.com/lvivski/gloss
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: '>=0.2.7'
  yaml: '0.9.0'
  path: '>=1.0.0 <2.0.0'
