name: gloss
version: 0.1.1
author: Yehor Lvivski <lvivski@gmail.com>
description: Glamorous CSS preprocessor
homepage: http://github.com/lvivski/gloss
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  unittest: '>=0.2.7'
